import { useEffect, useMemo, useState } from 'react';
import { BookOpenCheck, RefreshCw, Search } from 'lucide-react';

const API_BASE = (((window as any).__API_URL__ || import.meta.env.VITE_API_URL || 'http://localhost:5000') as string).replace(/\/$/, '');

const money = (n: any) => `Rs ${Number(n || 0).toLocaleString()}`;
const today = () => new Date().toISOString().slice(0, 10);
const monthStart = () => { const d = new Date(); return new Date(d.getFullYear(), d.getMonth(), 1).toISOString().slice(0, 10); };
export default function GeneralLedgerScreen() {
  const [startDate, setStartDate] = useState(monthStart());
  const [endDate, setEndDate] = useState(today());
  const [search, setSearch] = useState('');
  const [data, setData] = useState<any>({ rows: [], summary: {} });
  const load = async () => { const res = await fetch(`${API_BASE}/api/general-ledger?startDate=${startDate}&endDate=${endDate}`); setData(await res.json()); };
  useEffect(() => { load(); }, [startDate, endDate]);
  const rows = useMemo(() => (data.rows || []).filter((r:any) => !search || [r.module,r.reference,r.party,r.description].join(' ').toLowerCase().includes(search.toLowerCase())), [data, search]);
  return <div className="max-w-[1700px] mx-auto pb-10"><div className="bg-white rounded-2xl p-5 border shadow-sm mb-5 flex flex-col xl:flex-row xl:items-center justify-between gap-4"><div><h2 className="text-2xl font-black text-slate-900 flex items-center gap-2"><BookOpenCheck/> General Ledger</h2><p className="text-sm font-semibold text-slate-500 mt-1">Sales, purchases, payments, expenses aur salary ka complete audit trail.</p></div><div className="flex flex-wrap gap-2"><input type="date" value={startDate} onChange={e=>setStartDate(e.target.value)} className="border rounded-xl px-3 py-2 font-bold"/><input type="date" value={endDate} onChange={e=>setEndDate(e.target.value)} className="border rounded-xl px-3 py-2 font-bold"/><button onClick={load} className="bg-slate-900 text-white px-4 py-2 rounded-xl font-black flex gap-2"><RefreshCw size={16}/>Reload</button></div></div>
  <div className="grid grid-cols-1 md:grid-cols-4 gap-4 mb-5"><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Entries</p><p className="text-2xl font-black">{data.summary?.entries || 0}</p></div><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Debit</p><p className="text-2xl font-black text-rose-600">{money(data.summary?.debit)}</p></div><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Credit</p><p className="text-2xl font-black text-emerald-600">{money(data.summary?.credit)}</p></div><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Balance</p><p className="text-2xl font-black text-slate-900">{money(data.summary?.balance)}</p></div></div>
  <div className="bg-white rounded-2xl border shadow-sm overflow-hidden"><div className="p-4 bg-slate-50 border-b flex items-center"><Search size={16} className="mr-2 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search module, reference, party, description..." className="w-full bg-transparent outline-none font-bold text-sm"/></div><div className="overflow-x-auto"><table className="w-full min-w-[1100px] text-sm"><thead className="bg-slate-50 text-xs uppercase text-slate-400"><tr><th className="p-4 text-left">Date</th><th className="p-4 text-left">Module</th><th className="p-4 text-left">Reference</th><th className="p-4 text-left">Party</th><th className="p-4 text-left">Description</th><th className="p-4 text-right">Debit</th><th className="p-4 text-right">Credit</th><th className="p-4 text-right">Running Balance</th></tr></thead><tbody className="divide-y">{rows.map((r:any,i:number)=><tr key={i} className="hover:bg-slate-50"><td className="p-4 font-bold">{new Date(r.date).toLocaleString()}</td><td className="p-4 font-black text-indigo-600">{r.module}</td><td className="p-4 font-bold">{r.reference}</td><td className="p-4 font-bold">{r.party}</td><td className="p-4 text-slate-600">{r.description}</td><td className="p-4 text-right font-black text-rose-600">{r.debit ? money(r.debit) : '-'}</td><td className="p-4 text-right font-black text-emerald-600">{r.credit ? money(r.credit) : '-'}</td><td className="p-4 text-right font-black">{money(r.balance)}</td></tr>)}</tbody></table></div></div></div>;
}
