import { useEffect, useState } from 'react';
import { Save, HardDrive, RotateCcw, ShieldAlert, CheckCircle2, Database, RefreshCw, SlidersHorizontal, Lock, ShieldCheck, AlertTriangle } from 'lucide-react';

const API_BASE = (((window as any).__API_URL__ || import.meta.env.VITE_API_URL || 'http://localhost:5000') as string).replace(/\/$/, '');


export default function SettingsScreen() {
  const [settings, setSettings] = useState<any>({});
  const [backup, setBackup] = useState<any>({ backups: [] });
  const [system, setSystem] = useState<any>({});
  const [message, setMessage] = useState('');
  const [resetText, setResetText] = useState('');
  const [loading, setLoading] = useState(false);
  const [security, setSecurity] = useState({ username: '', password: '', pin: '' });

  const loadSettings = async () => {
    setLoading(true);
    try {
      const res = await fetch(`${API_BASE}/api/settings`);
      const data = await res.json();
      setSettings(data.settings || {}); setBackup(data.backup || { backups: [] }); setSystem(data.system || {});
    } catch { setMessage('Settings load nahi hui. Backend check karo.'); }
    finally { setLoading(false); }
  };
  useEffect(() => { loadSettings(); }, []);
  const update = (field: string, value: any) => setSettings((prev: any) => ({ ...prev, [field]: value }));
  const saveSettings = async () => {
    const safe = { ...settings, businessName: 'IQBAL JUTT TRADER' };
    const res = await fetch(`${API_BASE}/api/settings`, { method: 'PUT', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(safe) });
    const data = await res.json(); if (data.success) { setSettings(data.settings); setMessage('Settings saved. Brand name locked hai.'); } else setMessage(data.error || 'Settings save failed.');
  };
  const saveSecurity = async () => {
    if (!security.username && !security.password && !security.pin) return setMessage('Username, password ya PIN mein se koi value add karo.');
    const res = await fetch(`${API_BASE}/api/auth/update-admin`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(security) });
    const data = await res.json(); setMessage(data.message || data.error || 'Security updated'); setSecurity({ username: '', password: '', pin: '' });
  };
  const manualBackup = async () => { const res = await fetch(`${API_BASE}/api/settings/backup/manual`, { method: 'POST' }); const data = await res.json(); setMessage(data.message || data.error || 'Backup action completed.'); loadSettings(); };
  const resetAll = async () => {
    if (resetText !== 'RESET IQBAL JUTT') return setMessage('Reset ke liye exact text likho: RESET IQBAL JUTT');
    if (!window.confirm('Final warning: Ye complete business data fresh karega. Pre-reset backup banega. Continue?')) return;
    const res = await fetch(`${API_BASE}/api/settings/reset-all`, { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify({ confirm: resetText }) });
    const data = await res.json(); setMessage(data.message || data.error || 'Reset completed.'); setResetText(''); loadSettings();
  };

  return <div className="max-w-[1500px] mx-auto pb-10">
    <div className="bg-white rounded-2xl p-5 shadow-sm border border-slate-100 flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-6"><div><h2 className="text-2xl font-black text-slate-900 font-heading">Advanced Software Settings</h2><p className="text-sm text-slate-500 mt-1 font-semibold">Brand lock, login security, staff access, automatic backups, manual backup, and complete fresh reset.</p></div><button onClick={loadSettings} className="bg-[#0f172a] text-white px-5 py-2.5 rounded-xl font-bold text-sm flex items-center gap-2 w-fit"><RefreshCw size={16} /> Reload</button></div>
    {message && <div className="mb-5 bg-emerald-50 border border-emerald-200 rounded-xl px-4 py-3 text-sm font-bold text-emerald-700 flex items-center gap-2"><CheckCircle2 size={17} /> {message}</div>}
    {loading && <div className="bg-white p-10 rounded-2xl text-center text-slate-400 font-bold">Loading settings...</div>}
    <div className="grid grid-cols-1 xl:grid-cols-3 gap-5"><div className="xl:col-span-2 space-y-5">
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-5"><ShieldCheck size={18} /> Brand & Business Profile</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="text-sm font-bold text-slate-600">Brand Name Locked<input value="IQBAL JUTT TRADER" disabled className="mt-2 w-full border rounded-xl px-4 py-3 text-sm font-black bg-slate-100 text-slate-500" /></label><input value={settings.businessPhone || ''} onChange={e => update('businessPhone', e.target.value)} placeholder="Phone" className="border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500" /><input value={settings.city || ''} onChange={e => update('city', e.target.value)} placeholder="City" className="border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500" /><input value={settings.currency || 'Rs'} onChange={e => update('currency', e.target.value)} placeholder="Currency" className="border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500" /><textarea value={settings.businessAddress || ''} onChange={e => update('businessAddress', e.target.value)} placeholder="Business Address" className="md:col-span-2 border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500 min-h-[80px]" /><textarea value={settings.invoiceNote || ''} onChange={e => update('invoiceNote', e.target.value)} placeholder="Invoice Note" className="md:col-span-2 border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500 min-h-[80px]" /></div></div>
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-5"><Lock size={18} /> Admin Login / PIN Security</h3><div className="bg-amber-50 border border-amber-200 rounded-xl p-3 text-sm font-bold text-amber-800 mb-4">Default login pehli dafa admin/admin hota hai. Yahan se apna username, password aur PIN set kar lo.</div><div className="grid grid-cols-1 md:grid-cols-3 gap-4"><input value={security.username} onChange={e=>setSecurity({...security,username:e.target.value})} placeholder="New admin username" className="border rounded-xl px-4 py-3 text-sm font-semibold"/><input value={security.password} onChange={e=>setSecurity({...security,password:e.target.value})} placeholder="New admin password" className="border rounded-xl px-4 py-3 text-sm font-semibold"/><input value={security.pin} onChange={e=>setSecurity({...security,pin:e.target.value})} placeholder="New PIN" className="border rounded-xl px-4 py-3 text-sm font-semibold"/></div><button onClick={saveSecurity} className="mt-5 bg-slate-900 hover:bg-slate-800 text-white px-5 py-2.5 rounded-xl font-bold text-sm flex items-center gap-2"><Lock size={16} /> Save Login Settings</button></div>
      <div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-5"><SlidersHorizontal size={18} /> Software Controls</h3><div className="grid grid-cols-1 md:grid-cols-2 gap-4"><label className="text-sm font-bold text-slate-600">Low Stock Alert Level<input type="number" value={settings.lowStockLevel || 10} onChange={e => update('lowStockLevel', Number(e.target.value))} className="mt-2 w-full border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500" /></label><label className="text-sm font-bold text-slate-600">Daily Backup Time<input value={settings.backupTime || '23:30'} onChange={e => update('backupTime', e.target.value)} className="mt-2 w-full border rounded-xl px-4 py-3 text-sm font-semibold outline-none focus:border-emerald-500" /></label><label className="flex items-center gap-3 bg-slate-50 border rounded-xl px-4 py-3 text-sm font-bold text-slate-700"><input type="checkbox" checked={!!settings.autoBackupEnabled} onChange={e => update('autoBackupEnabled', e.target.checked)} /> Automatic Daily Backup Enabled</label><label className="flex items-center gap-3 bg-slate-50 border rounded-xl px-4 py-3 text-sm font-bold text-slate-700"><input type="checkbox" checked={!!settings.allowDataReset} onChange={e => update('allowDataReset', e.target.checked)} /> Allow Fresh Data Reset Button</label></div><button onClick={saveSettings} className="mt-5 bg-emerald-600 hover:bg-emerald-700 text-white px-5 py-2.5 rounded-xl font-bold text-sm flex items-center gap-2"><Save size={16} /> Save Settings</button></div>
    </div><div className="space-y-5"><div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-4"><Database size={18} /> System Data</h3><div className="grid grid-cols-2 gap-3">{Object.entries(system).map(([k, v]: any) => <div key={k} className="bg-slate-50 rounded-xl p-3"><p className="text-[10px] uppercase font-black text-slate-400">{k}</p><p className="font-black text-slate-900 text-lg">{Number(v || 0).toLocaleString()}</p></div>)}</div></div><div className="bg-white rounded-2xl border border-slate-100 shadow-sm p-5"><h3 className="font-black text-slate-900 flex items-center gap-2 mb-4"><HardDrive size={18} /> Backup Control</h3><p className="text-sm text-slate-500 mb-4 font-semibold">Daily automatic backup server startup par check hota hai. Manual backup se foran database copy save hoti hai.</p><button onClick={manualBackup} className="w-full bg-[#0f172a] text-white px-5 py-3 rounded-xl font-bold text-sm flex items-center justify-center gap-2"><HardDrive size={16} /> Create Manual Backup</button><div className="mt-4 text-xs text-slate-500 font-semibold">Total Backups: {backup.totalBackups || 0}</div><div className="mt-3 max-h-[160px] overflow-y-auto custom-scrollbar space-y-2">{(backup.backups || []).slice(0, 8).map((b: any) => <div key={b.fileName} className="bg-slate-50 rounded-lg p-2 text-xs"><p className="font-bold text-slate-700 truncate">{b.fileName}</p><p className="text-slate-400">{new Date(b.createdAt).toLocaleString()}</p></div>)}</div></div><div className="bg-rose-50 rounded-2xl border border-rose-200 shadow-sm p-5"><h3 className="font-black text-rose-700 flex items-center gap-2 mb-3"><ShieldAlert size={18} /> Fresh Data Reset</h3><p className="text-sm text-rose-600 font-semibold mb-4">Ye sales, purchases, inventory, khata, customers, suppliers, expenses, staff salary payments, committees aur reports data fresh karega. Reset se pehle automatic pre-reset backup banega.</p><input value={resetText} onChange={e => setResetText(e.target.value)} placeholder="Type: RESET IQBAL JUTT" className="w-full border border-rose-200 rounded-xl px-4 py-3 text-sm font-bold outline-none focus:border-rose-500 mb-3" /><button onClick={resetAll} className="w-full bg-rose-600 hover:bg-rose-700 text-white px-5 py-3 rounded-xl font-black text-sm flex items-center justify-center gap-2"><RotateCcw size={16} /> Fresh / Reset All Business Data</button><div className="flex items-start gap-2 mt-3 text-xs text-rose-600 font-semibold"><AlertTriangle size={15} className="shrink-0" /> User accounts/settings safe rahenge; business records reset honge.</div></div></div></div>
  </div>;
}
