import { useEffect, useMemo, useState } from 'react';
import { UserCog, Plus, Trash2, Edit, X, Save, Banknote } from 'lucide-react';

const API_BASE = (((window as any).__API_URL__ || import.meta.env.VITE_API_URL || 'http://localhost:5000') as string).replace(/\/$/, '');


const sections = ['Dashboard','POS & Billing','Sales Register','Purchases','Inventory','Suppliers','Khata & Accounts','Committees (Besi)','Expenses','Quotations','General Ledger','Reports','Staff','Settings / RBAC'];
const blank = { name:'', phone:'', cnic:'', salary:'', address:'', username:'', password:'1234', pin:'1234', role:'STAFF', status:'ACTIVE', profileImage:'', permissions:['POS & Billing'] };
const money = (n:any)=>`Rs ${Number(n||0).toLocaleString()}`;

export default function StaffScreen(){
  const [rows,setRows]=useState<any[]>([]); const [open,setOpen]=useState(false); const [editing,setEditing]=useState<any>(null); const [form,setForm]=useState<any>(blank); const [salaryStaff,setSalaryStaff]=useState<any>(null); const [salaryRows,setSalaryRows]=useState<any[]>([]); const [payment,setPayment]=useState({amount:'',salaryMonth:new Date().toISOString().slice(0,7),paymentDate:new Date().toISOString().slice(0,10),paymentMethod:'CASH',notes:''});
  const load=async()=>{const res=await fetch(`${API_BASE}/api/staff`); const data=await res.json(); setRows(data.rows||[])};
  useEffect(()=>{load()},[]);
  const totalSalary=useMemo(()=>rows.reduce((a,r)=>a+Number(r.salary||0),0),[rows]);
  const openNew=()=>{setEditing(null); setForm(blank); setOpen(true)};
  const openEdit=(r:any)=>{setEditing(r); setForm({...blank,...r, username:r.username||'', password:'', permissions:r.permissions||[]}); setOpen(true)};
  const save=async()=>{if(!form.name) return alert('Staff name required'); const url=editing?`${API_BASE}/api/staff/${editing.id}`:`${API_BASE}/api/staff`; const res=await fetch(url,{method:editing?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)}); const data=await res.json(); if(data.error) return alert(data.error); setOpen(false); load()};
  const del=async(id:number)=>{if(!confirm('Staff delete karna hai?'))return; await fetch(`${API_BASE}/api/staff/${id}`,{method:'DELETE'}); load()};
  const loadSalary=async(staff:any)=>{setSalaryStaff(staff); const res=await fetch(`${API_BASE}/api/staff/${staff.id}/salary`); const data=await res.json(); setSalaryRows(data.rows||[])};
  const paySalary=async()=>{if(!payment.amount) return alert('Amount required'); const res=await fetch(`${API_BASE}/api/staff/${salaryStaff.id}/salary`,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payment)}); const data=await res.json(); if(data.error) return alert(data.error); setPayment({...payment,amount:'',notes:''}); loadSalary(salaryStaff)};
  const togglePerm=(s:string)=>setForm((p:any)=>({...p,permissions:p.permissions?.includes(s)?p.permissions.filter((x:string)=>x!==s):[...(p.permissions||[]),s]}));
  return <div className="max-w-[1600px] mx-auto pb-10"><div className="bg-white rounded-2xl p-5 border shadow-sm flex flex-col lg:flex-row lg:items-center justify-between gap-4 mb-5"><div><h2 className="text-2xl font-black text-slate-900 flex gap-2"><UserCog/> Staff & Permissions</h2><p className="text-sm text-slate-500 font-semibold mt-1">Staff profile, salary flow aur section-wise login restrictions.</p></div><button onClick={openNew} className="bg-slate-900 text-white rounded-xl px-5 py-3 font-black flex gap-2 w-fit"><Plus size={17}/> Add Staff</button></div>
  <div className="grid grid-cols-1 md:grid-cols-3 gap-4 mb-5"><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Total Staff</p><p className="text-2xl font-black">{rows.length}</p></div><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Monthly Salary Load</p><p className="text-2xl font-black text-emerald-600">{money(totalSalary)}</p></div><div className="bg-white rounded-2xl p-5 border"><p className="text-xs font-black text-slate-400 uppercase">Active Staff</p><p className="text-2xl font-black text-indigo-600">{rows.filter(r=>r.status==='ACTIVE').length}</p></div></div>
  <div className="grid grid-cols-1 md:grid-cols-2 xl:grid-cols-3 gap-4">{rows.map(r=><div key={r.id} className="bg-white rounded-2xl p-5 border shadow-sm"><div className="flex gap-4"><div className="w-16 h-16 rounded-2xl bg-slate-100 overflow-hidden flex items-center justify-center font-black text-slate-400">{r.profileImage?<img src={r.profileImage} className="w-full h-full object-cover"/>:r.name?.[0]}</div><div className="flex-1"><h3 className="font-black text-slate-900">{r.name}</h3><p className="text-xs font-bold text-slate-500">{r.phone || '-'} • {r.cnic || '-'}</p><p className="text-xs font-black text-emerald-600 mt-1">{r.username} / {r.role}</p></div></div><div className="mt-4 grid grid-cols-2 gap-2 text-sm"><div className="bg-slate-50 rounded-xl p-3"><p className="text-[10px] font-black text-slate-400">Salary</p><p className="font-black">{money(r.salary)}</p></div><div className="bg-slate-50 rounded-xl p-3"><p className="text-[10px] font-black text-slate-400">Permissions</p><p className="font-black">{r.permissions?.includes('ALL')?'ALL':r.permissions?.length||0}</p></div></div><div className="mt-4 flex gap-2"><button onClick={()=>openEdit(r)} className="bg-amber-500 text-white rounded-xl px-3 py-2 font-black flex gap-1"><Edit size={15}/>Edit</button><button onClick={()=>loadSalary(r)} className="bg-emerald-600 text-white rounded-xl px-3 py-2 font-black flex gap-1"><Banknote size={15}/>Pay Salary</button><button onClick={()=>del(r.id)} className="bg-rose-600 text-white rounded-xl px-3 py-2 font-black"><Trash2 size={15}/></button></div></div>)}</div>
  {open&&<div className="fixed inset-0 bg-slate-900/50 z-[999] p-4 overflow-y-auto"><div className="bg-white rounded-2xl max-w-5xl mx-auto p-5 shadow-2xl"><div className="flex justify-between mb-4"><h3 className="font-black text-xl">{editing?'Edit Staff':'Add Staff'}</h3><button onClick={()=>setOpen(false)}><X/></button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3"><input value={form.name} onChange={e=>setForm({...form,name:e.target.value})} placeholder="Full name" className="border rounded-xl p-3 font-bold"/><input value={form.phone} onChange={e=>setForm({...form,phone:e.target.value})} placeholder="Phone" className="border rounded-xl p-3 font-bold"/><input value={form.cnic} onChange={e=>setForm({...form,cnic:e.target.value})} placeholder="CNIC" className="border rounded-xl p-3 font-bold"/><input type="number" value={form.salary} onChange={e=>setForm({...form,salary:e.target.value})} placeholder="Monthly salary" className="border rounded-xl p-3 font-bold"/><input value={form.username} onChange={e=>setForm({...form,username:e.target.value})} placeholder="Login username" className="border rounded-xl p-3 font-bold"/><input value={form.password} onChange={e=>setForm({...form,password:e.target.value})} placeholder={editing?'New password optional':'Password'} className="border rounded-xl p-3 font-bold"/><input value={form.pin} onChange={e=>setForm({...form,pin:e.target.value})} placeholder="PIN" className="border rounded-xl p-3 font-bold"/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})} className="border rounded-xl p-3 font-bold"><option>STAFF</option><option>CASHIER</option><option>ADMIN</option></select><select value={form.status} onChange={e=>setForm({...form,status:e.target.value})} className="border rounded-xl p-3 font-bold"><option>ACTIVE</option><option>INACTIVE</option></select><textarea value={form.address} onChange={e=>setForm({...form,address:e.target.value})} placeholder="Address" className="md:col-span-3 border rounded-xl p-3 font-bold"/></div><h4 className="mt-5 font-black text-slate-900">Allowed Sections</h4><div className="mt-3 grid grid-cols-2 md:grid-cols-4 gap-2">{sections.map(s=><label key={s} className="bg-slate-50 border rounded-xl px-3 py-2 text-xs font-black flex gap-2"><input type="checkbox" checked={form.permissions?.includes(s) || form.permissions?.includes('ALL')} onChange={()=>togglePerm(s)}/>{s}</label>)}<label className="bg-emerald-50 border border-emerald-200 rounded-xl px-3 py-2 text-xs font-black flex gap-2"><input type="checkbox" checked={form.permissions?.includes('ALL')} onChange={()=>setForm({...form,permissions:form.permissions?.includes('ALL')?[]:['ALL']})}/>ALL Permissions</label></div><button onClick={save} className="mt-5 bg-emerald-600 text-white rounded-xl px-6 py-3 font-black flex gap-2"><Save size={17}/>Save Staff</button></div></div>}
  {salaryStaff&&<div className="fixed inset-0 bg-slate-900/50 z-[999] flex items-center justify-center p-4"><div className="bg-white rounded-2xl max-w-3xl w-full p-5 shadow-2xl"><div className="flex justify-between"><h3 className="font-black text-xl">Salary Payment — {salaryStaff.name}</h3><button onClick={()=>setSalaryStaff(null)}><X/></button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-3 mt-4"><input type="number" value={payment.amount} onChange={e=>setPayment({...payment,amount:e.target.value})} placeholder="Amount" className="border rounded-xl p-3 font-bold"/><input type="month" value={payment.salaryMonth} onChange={e=>setPayment({...payment,salaryMonth:e.target.value})} className="border rounded-xl p-3 font-bold"/><input type="date" value={payment.paymentDate} onChange={e=>setPayment({...payment,paymentDate:e.target.value})} className="border rounded-xl p-3 font-bold"/><select value={payment.paymentMethod} onChange={e=>setPayment({...payment,paymentMethod:e.target.value})} className="border rounded-xl p-3 font-bold"><option>CASH</option><option>BANK</option><option>JAZZCASH</option><option>EASYPAISA</option></select><input value={payment.notes} onChange={e=>setPayment({...payment,notes:e.target.value})} placeholder="Notes" className="md:col-span-2 border rounded-xl p-3 font-bold"/></div><button onClick={paySalary} className="mt-4 bg-emerald-600 text-white rounded-xl px-5 py-3 font-black">Save Salary Payment</button><div className="mt-5 max-h-[260px] overflow-y-auto divide-y">{salaryRows.map(r=><div key={r.id} className="py-3 flex justify-between"><div><p className="font-black">{money(r.amount)}</p><p className="text-xs text-slate-400 font-bold">{r.salaryMonth} • {new Date(r.paymentDate).toLocaleDateString()}</p></div><p className="font-bold text-slate-500">{r.paymentMethod}</p></div>)}</div></div></div>}
  </div>;
}
